oracle-livelabs/pts

- sharding-quick-start/setup-environment/setup-environment.md
WMS ID #6602 - Oracle Sharding Quick Start, upgrade the terraform script
> WMS ID #6602 - Oracle Sharding Quick Start, upgrade the terraform script

- oml4r/oml4r-workshop/oml4r-workshop.md
Added ggplot2 library. Organized Task 6 (marked steps 10 and 11 individually). Added further details elsewhere.
> WMS ID #6942:Update_oml4r-workshop.md

- python-fullstack-todolist-using-oke/setup-dev-environment/setup-dev-environment.md
WMSID: 8442 Python Fullstack OKE workshop
> WMSID: 8442 -  Corrected the OKE repository path

- python-fullstack-todolist-using-oke/setup-dev-environment/setup-dev-environment.md
WMS ID  8442 - Corrected the OKE repository path
> WMS ID 8422 Update setup-dev-environment.md 

- mongo-api/cleanup-ocw/cleanup-free-ocw.md
- mongo-api/infra-ocw/infra-free-ocw.md
- mongo-api/mongo-api-ocw/mongo-api-free-ocw.md
- mongo-api/simple-app-ocw/simple-app-free-ocw.md
- mongo-api/workshops/ocw-freetier/manifest.json
> ID5307 - Added walkthrough videos

- sharding/workshops/ocw-freetier/index.html
- sharding/workshops/ocw-freetier/manifest.json
> WMS 5241: Fix OCW manifest

- sharding/shard-db-deployment/shard-db-deployment.md
> WMS ID 5241: fixed the copy tag

- sharding/setup-environment/setup-environment.md
> upgrade the terraform scripts

- on-premise-19c-adg/workshops/freetier/manifest.json
> ID#5521 - Setting Up Active Data Guard For On-Premises QA

- hybrid-adg/setup-environment/setup-environment.md
WMS ID#1160: Oracle Database Hybrid Active Data Guard.
> WMS ID#1160: modified to DB19.20

- sharding/setup-environment/setup-environment.md
WMS ID#5241 Oracle Globally Distributed Database
> WMS ID#5241 Oracle Globally Distributed Database: upgrade to DB19.20

- hybrid-adg/introduction/introduction.md
- hybrid-adg/test-with-adg/test-with-adg.md
- hybrid-adg/workshops/freetier/manifest.json
> ID#1160 QUARTERLY QA

- plsql-rag-23ai/introduction/introduction.md
- plsql-rag-23ai/lab1/lab1.md
Implementing changes suggested by Doug Hood.
> WMSID:11620 - Complete RAG application with Oracle AI Vector Search and PLSQL

- ai-vector-embedding-python/labs/labs.md
> Update labs.md 11618: AI Vector Embedding for Python

- ai-vector-embedding-python/labs/labs.md
- [Y ] All filenames are lower case (including folders, images, files, etc.)
- [Y ] Filenames are descriptive
- [Y ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ Y] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ Y] Image references in …
>  Update labs.md 11618: AI Vector Embedding for Python

- ai-vector-embedding-jdbc/labs/labs.md
- ai-vector-embedding-jdbc/workshops/desktop/index.html
- ai-vector-embedding-jdbc/workshops/desktop/manifest.json
- ai-vector-embedding-jdbc/workshops/sandbox/manifest.json
- ai-vector-embedding-jdbc/workshops/tenancy/manifest.json
- [ y] All filenames are lower case (including folders, images, files, etc.)
- [ y] Filenames are descriptive
- [y ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ y] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [y ] Image references in …
> WMS ID 11636 AI Vector Search JDBC - fixed desktop folder

- ai-vector-search-basic/workshops/desktop/manifest15.json
> AI Vector Search 15 Minute LiveLab

- ai-vector-search-basic/workshops/desktop15/manifest.json
> wid:3975: Adding link to access Sandbox instance and NoVNC URL

- ai-vector-search-apex-adb/apex-app/apex-app.md
- ai-vector-search-apex-adb/apex/apex.md
> wmsid# 11631 - updated contributors and Authors. 

- mongo-api/manifest.json
- mongo-api/workshops/ocw-freetier/manifest.json
- mongo-api/workshops/ocw-livelabs/manifest.json
- mongo-api/workshops/ocw23-sandbox/manifest.json
- mongo-api/workshops/ocw23-tenancy/manifest.json
> Removing all OCW support labs from workshop manifests

- ai-vector-embedding-jdbc/common/common.md
- ai-vector-search-basic/introduction/introduction.md
- ai-vector-search-basic/lab2/vector_distance.md
- audit/custom-audit-events/audit-events.md
- audit/introduction/introduction.md
- langchain-rag-23ai/lab1/lab1.md
- langchain-rag-23ai/lab2/lab2.md
> Correct Oracle Database 23ai mention
